---
# tasks file for ignite
- name: add ignite group
  become: yes
  become_user: root
  group:
    name: ignite
    state: present

- name: add ignite user
  become: yes
  become_user: root
  user:
    name: ignite
    group: ignite
    home: '{{ignite_home}}'

- name: download ignite
  become: yes
  become_user: ignite
  get_url:
    url: '{{ignite_url}}'
    dest: '{{ignite_home}}/{{ignite_zip}}'
    mode: 0644

- name: unarchive
  become: yes
  become_user: ignite
  unarchive:
    remote_src: yes
    src: '{{ignite_home}}/{{ignite_zip}}'
    dest: '{{ignite_home}}'
    creates: '{{ignite_home}}/{{ignite_name}}'

- name: install config
  become: yes
  become_user: ignite
  with_items:
    - f: default-config.xml
      d: '{{ignite_home}}/{{ignite_name}}/config'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m|default("0644")}}'

- include_tasks: '{{ignite_supervisor|default("systemd")}}.yml'
