---
# tasks file for ignite
- name: add ignite group
  group: name=ignite state=present

- name: add ignite user
  user: >
    name=ignite
    group=ignite
    home={{ignite_home}}

- name: download ignite
  get_url: >-
    url={{ignite_url}}
    dest={{ignite_home}}/{{ignite_zip}}
    owner=ignite
    group=ignite
    mode=644

- name: unarchive
  unarchive: >-
    copy=no
    src={{ignite_home}}/{{ignite_zip}}
    dest={{ignite_home}}
    owner=ignite
    group=ignite
    creates={{ignite_home}}/{{ignite_name}}

- name: install config
  template: >-
    src=config/default-config.xml.j2
    dest={{ignite_home}}/{{ignite_name}}/config/default-config.xml
    owner=ignite
    group=ignite
    mode=0644
    
